package model;
// Generated Nov 28, 2025 6:28:07 PM by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "buku")

/**
 * Buku generated by hbm2java
 */
public class Buku implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name = "id")
    private Integer id;

    @Column(name = "judul")
    private String judul;

    @Column(name = "penulis")
    private String penulis;

    @Column(name = "kategori")
    private String kategori;

    @Column(name = "tahun")
    private Integer tahun;

    public Buku() {
    }

    public Buku(String judul, String penulis, String kategori, Integer tahun) {
       this.judul = judul;
       this.penulis = penulis;
       this.kategori = kategori;
       this.tahun = tahun;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getPenulis() {
        return this.penulis;
    }
    
    public void setPenulis(String penulis) {
        this.penulis = penulis;
    }
    public String getKategori() {
        return this.kategori;
    }
    
    public void setKategori(String kategori) {
        this.kategori = kategori;
    }
    public Integer getTahun() {
        return this.tahun;
    }
    
    public void setTahun(Integer tahun) {
        this.tahun = tahun;
    }

    public String toString() {
        return "Buku(" +
                "id=" + id +
                ", judul='" + judul + '\'' +
                ", penulis='" + penulis + '\'' +
                ", kategori='" + kategori + '\'' +
                ", tahun=" + tahun +
                ')';
    }

}


